import type { ShoppingItem } from "@prisma/client";
import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [items, setItems] = useState<ShoppingItem[]>([]);

  const {} = trpc.useMutation(["items.addItem"], {
    onSuccess: (item) => {
      setItems((prev) => [...prev, item]);
    },
  });
  // const {} = trpc.useMutation(["items.addItem"], {
  //   onSuccess: (item) => {
  //     setItems((prev) => [...prev, item]);
  //   },
  // });

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="mx-5 rounded-md bg-violet-500 px-8 py-2 text-white transition hover:bg-violet-600"
          >
            Add Shopping
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => (
            // eslint-disable-next-line react/jsx-key
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
